name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Prettier Check
        run: npm run format:check
      - name: Lint (ESLint)
        run: npm run lint
      - name: Lint Styles (Stylelint)
        run: npm run lint:styles
      - name: Unit/UI Tests (Vitest)
        run: npm test
      - name: Install Playwright Browsers
        working-directory: frontend
        run: npx playwright install --with-deps
      - name: E2E Tests (Playwright)
        working-directory: frontend
        run: npm run e2e
      - name: Build
        run: npm run build
