name: PR Title - Conventional Commits

on:
  pull_request:

jobs:
  commitlint-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Lint PR title with commitlint
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: |
          echo "$PR_TITLE" | npx --yes @commitlint/cli@19.3.0 --config commitlint.config.cjs
